import { useBaklavaTheme } from "@baklavue/composables";
import * as BaklaVue from "@baklavue/ui";
import "@trendyol/baklava/dist/themes/default.css";
import Theme from "vitepress/theme";
import AlertProgrammaticDemo from "./components/AlertProgrammaticDemo.vue";
import CheckboxCustomSlotDemo from "./components/CheckboxCustomSlotDemo.vue";
import CheckboxDisabledDemo from "./components/CheckboxDisabledDemo.vue";
import CheckboxGroupDemo from "./components/CheckboxGroupDemo.vue";
import CheckboxPreferencesDemo from "./components/CheckboxPreferencesDemo.vue";
import CheckboxSingleDemo from "./components/CheckboxSingleDemo.vue";
import ClosableAlertDemo from "./components/ClosableAlertDemo.vue";
import ControlledAccordionDemo from "./components/ControlledAccordionDemo.vue";
import CustomAnimationDemo from "./components/CustomAnimationDemo.vue";
import DatepickerDemo from "./components/DatepickerDemo.vue";
import DialogBasicDemo from "./components/DialogBasicDemo.vue";
import DialogCaptionDemo from "./components/DialogCaptionDemo.vue";
import DialogClosableDemo from "./components/DialogClosableDemo.vue";
import DialogHeaderFooterDemo from "./components/DialogHeaderFooterDemo.vue";
import DialogProgrammaticDemo from "./components/DialogProgrammaticDemo.vue";
import DrawerBasicDemo from "./components/DrawerBasicDemo.vue";
import DropdownBasicDemo from "./components/DropdownBasicDemo.vue";
import DropdownDisabledDemo from "./components/DropdownDisabledDemo.vue";
import DropdownGroupDemo from "./components/DropdownGroupDemo.vue";
import DropdownItemsDemo from "./components/DropdownItemsDemo.vue";
import DropdownProgrammaticDemo from "./components/DropdownProgrammaticDemo.vue";
import DropdownSlotDemo from "./components/DropdownSlotDemo.vue";
import DrawerCaptionDemo from "./components/DrawerCaptionDemo.vue";
import DrawerProgrammaticDemo from "./components/DrawerProgrammaticDemo.vue";
import DynamicItemsDemo from "./components/DynamicItemsDemo.vue";
import FaqSlotsDemo from "./components/FaqSlotsDemo.vue";
import FormSubmitButtonDemo from "./components/FormSubmitButtonDemo.vue";
import IconBasicDemo from "./components/IconBasicDemo.vue";
import IconColorDemo from "./components/IconColorDemo.vue";
import IconSizeDemo from "./components/IconSizeDemo.vue";
import InputBasicDemo from "./components/InputBasicDemo.vue";
import InputDisabledReadonlyDemo from "./components/InputDisabledReadonlyDemo.vue";
import InputFormValidationDemo from "./components/InputFormValidationDemo.vue";
import InputHelpTextDemo from "./components/InputHelpTextDemo.vue";
import InputLoadingDemo from "./components/InputLoadingDemo.vue";
import InputSizesDemo from "./components/InputSizesDemo.vue";
import InputTypesDemo from "./components/InputTypesDemo.vue";
import InputValidationDemo from "./components/InputValidationDemo.vue";
import InputWithIconDemo from "./components/InputWithIconDemo.vue";
import LinkBasicDemo from "./components/LinkBasicDemo.vue";
import LinkDisabledDemo from "./components/LinkDisabledDemo.vue";
import LinkExternalDemo from "./components/LinkExternalDemo.vue";
import LinkInlineDemo from "./components/LinkInlineDemo.vue";
import LinkSizesDemo from "./components/LinkSizesDemo.vue";
import LinkStandaloneDemo from "./components/LinkStandaloneDemo.vue";
import LinkWithIconDemo from "./components/LinkWithIconDemo.vue";
import LoadingButtonDemo from "./components/LoadingButtonDemo.vue";
import NotificationBasicDemo from "./components/NotificationBasicDemo.vue";
import NotificationDurationDemo from "./components/NotificationDurationDemo.vue";
import PaginationBasicDemo from "./components/PaginationBasicDemo.vue";
import PaginationJumperDemo from "./components/PaginationJumperDemo.vue";
import PaginationSelectDemo from "./components/PaginationSelectDemo.vue";
import ProgrammaticControlDemo from "./components/ProgrammaticControlDemo.vue";
import SelectBasicDemo from "./components/SelectBasicDemo.vue";
import SelectDisabledDemo from "./components/SelectDisabledDemo.vue";
import SelectMultipleDemo from "./components/SelectMultipleDemo.vue";
import SelectOptionsDemo from "./components/SelectOptionsDemo.vue";
import SelectSizesDemo from "./components/SelectSizesDemo.vue";
import SlotsAccordionDemo from "./components/SlotsAccordionDemo.vue";
import SpinnerBasicDemo from "./components/SpinnerBasicDemo.vue";
import SpinnerSizesDemo from "./components/SpinnerSizesDemo.vue";
import SpinnerVariantsDemo from "./components/SpinnerVariantsDemo.vue";
import SplitButtonBasicDemo from "./components/SplitButtonBasicDemo.vue";
import SplitButtonDropdownDemo from "./components/SplitButtonDropdownDemo.vue";
import SplitButtonWithIconDemo from "./components/SplitButtonWithIconDemo.vue";
import StepperBasicDemo from "./components/StepperBasicDemo.vue";
import StepperChangeEventDemo from "./components/StepperChangeEventDemo.vue";
import StepperDescriptionDemo from "./components/StepperDescriptionDemo.vue";
import StepperDisabledDemo from "./components/StepperDisabledDemo.vue";
import StepperErrorDemo from "./components/StepperErrorDemo.vue";
import StepperFormWizardDemo from "./components/StepperFormWizardDemo.vue";
import StepperNoLabelsDemo from "./components/StepperNoLabelsDemo.vue";
import StepperOrientationDemo from "./components/StepperOrientationDemo.vue";
import StepperWithStepsDemo from "./components/StepperWithStepsDemo.vue";
import SwitchBasicDemo from "./components/SwitchBasicDemo.vue";
import SwitchDisabledDemo from "./components/SwitchDisabledDemo.vue";
import SwitchSizesDemo from "./components/SwitchSizesDemo.vue";
import "./style.css";

export default {
  extends: Theme,
  enhanceApp({ app }) {
    useBaklavaTheme().applyTheme({ preset: "vue" });
    app.component("AlertProgrammaticDemo", AlertProgrammaticDemo);
    app.component("CheckboxCustomSlotDemo", CheckboxCustomSlotDemo);
    app.component("CheckboxDisabledDemo", CheckboxDisabledDemo);
    app.component("CheckboxGroupDemo", CheckboxGroupDemo);
    app.component("CheckboxPreferencesDemo", CheckboxPreferencesDemo);
    app.component("CheckboxSingleDemo", CheckboxSingleDemo);
    app.component("ClosableAlertDemo", ClosableAlertDemo);
    app.component("ControlledAccordionDemo", ControlledAccordionDemo);
    app.component("CustomAnimationDemo", CustomAnimationDemo);
    app.component("DatepickerDemo", DatepickerDemo);
    app.component("DialogBasicDemo", DialogBasicDemo);
    app.component("DialogCaptionDemo", DialogCaptionDemo);
    app.component("DialogClosableDemo", DialogClosableDemo);
    app.component("DialogHeaderFooterDemo", DialogHeaderFooterDemo);
    app.component("DialogProgrammaticDemo", DialogProgrammaticDemo);
    app.component("DrawerBasicDemo", DrawerBasicDemo);
    app.component("DrawerCaptionDemo", DrawerCaptionDemo);
    app.component("DropdownBasicDemo", DropdownBasicDemo);
    app.component("DropdownDisabledDemo", DropdownDisabledDemo);
    app.component("DropdownGroupDemo", DropdownGroupDemo);
    app.component("DropdownItemsDemo", DropdownItemsDemo);
    app.component("DropdownProgrammaticDemo", DropdownProgrammaticDemo);
    app.component("DropdownSlotDemo", DropdownSlotDemo);
    app.component("DrawerProgrammaticDemo", DrawerProgrammaticDemo);
    app.component("DynamicItemsDemo", DynamicItemsDemo);
    app.component("FaqSlotsDemo", FaqSlotsDemo);
    app.component("FormSubmitButtonDemo", FormSubmitButtonDemo);
    app.component("IconBasicDemo", IconBasicDemo);
    app.component("IconColorDemo", IconColorDemo);
    app.component("IconSizeDemo", IconSizeDemo);
    app.component("InputBasicDemo", InputBasicDemo);
    app.component("InputDisabledReadonlyDemo", InputDisabledReadonlyDemo);
    app.component("InputFormValidationDemo", InputFormValidationDemo);
    app.component("InputHelpTextDemo", InputHelpTextDemo);
    app.component("InputLoadingDemo", InputLoadingDemo);
    app.component("InputSizesDemo", InputSizesDemo);
    app.component("InputTypesDemo", InputTypesDemo);
    app.component("InputValidationDemo", InputValidationDemo);
    app.component("InputWithIconDemo", InputWithIconDemo);
    app.component("LinkBasicDemo", LinkBasicDemo);
    app.component("LinkDisabledDemo", LinkDisabledDemo);
    app.component("LinkExternalDemo", LinkExternalDemo);
    app.component("LinkInlineDemo", LinkInlineDemo);
    app.component("LinkSizesDemo", LinkSizesDemo);
    app.component("LinkStandaloneDemo", LinkStandaloneDemo);
    app.component("LinkWithIconDemo", LinkWithIconDemo);
    app.component("LoadingButtonDemo", LoadingButtonDemo);
    app.component("NotificationBasicDemo", NotificationBasicDemo);
    app.component("NotificationDurationDemo", NotificationDurationDemo);
    app.component("PaginationBasicDemo", PaginationBasicDemo);
    app.component("PaginationJumperDemo", PaginationJumperDemo);
    app.component("PaginationSelectDemo", PaginationSelectDemo);
    app.component("ProgrammaticControlDemo", ProgrammaticControlDemo);
    app.component("SelectBasicDemo", SelectBasicDemo);
    app.component("SelectDisabledDemo", SelectDisabledDemo);
    app.component("SelectMultipleDemo", SelectMultipleDemo);
    app.component("SelectOptionsDemo", SelectOptionsDemo);
    app.component("SelectSizesDemo", SelectSizesDemo);
    app.component("SlotsAccordionDemo", SlotsAccordionDemo);
    app.component("SpinnerBasicDemo", SpinnerBasicDemo);
    app.component("SpinnerSizesDemo", SpinnerSizesDemo);
    app.component("SpinnerVariantsDemo", SpinnerVariantsDemo);
    app.component("SplitButtonBasicDemo", SplitButtonBasicDemo);
    app.component("SplitButtonDropdownDemo", SplitButtonDropdownDemo);
    app.component("SplitButtonWithIconDemo", SplitButtonWithIconDemo);
    app.component("StepperBasicDemo", StepperBasicDemo);
    app.component("StepperChangeEventDemo", StepperChangeEventDemo);
    app.component("StepperDescriptionDemo", StepperDescriptionDemo);
    app.component("StepperDisabledDemo", StepperDisabledDemo);
    app.component("StepperErrorDemo", StepperErrorDemo);
    app.component("StepperFormWizardDemo", StepperFormWizardDemo);
    app.component("StepperNoLabelsDemo", StepperNoLabelsDemo);
    app.component("StepperOrientationDemo", StepperOrientationDemo);
    app.component("StepperWithStepsDemo", StepperWithStepsDemo);
    app.component("SwitchBasicDemo", SwitchBasicDemo);
    app.component("SwitchDisabledDemo", SwitchDisabledDemo);
    app.component("SwitchSizesDemo", SwitchSizesDemo);
    // Register all BaklaVue components globally
    // Components are exported with "Bv" prefix (e.g., BvAccordion)
    // Register them with both prefixed and non-prefixed names
    for (const [key, component] of Object.entries(BaklaVue)) {
      if (key.startsWith("Bv") && typeof component !== "function") {
        // Register with prefixed name (BvAccordion)
        app.component(key, component);
        // Also register without prefix (Accordion) for convenience
        const name = key.replace(/^Bv/, "");
        app.component(name, component);
      }
    }
  },
};
